<?php

function ohano_tracker_preprocess_html(&$variables) {
}

/**
 * Implements hook_developer_mode_info_alter().
 */
function ohano_tracker_developer_mode_info_alter(&$developer_mode_info) {
  $url = \Drupal::request()->getRequestUri();
  /** @var Drupal\Core\Entity\Query\Sql\Query $viewsQuery */
  $viewsQuery = \Drupal::entityQuery(\Drupal\ohano_tracker\Entity\PathRequest::ENTITY_ID)
    ->condition('path', $url, '=');
  $views = count($viewsQuery->execute());
  $developer_mode_info['ohano_tracker'] = [
    'route' => $url,
    'views' => $views,
    'query' => (string) $viewsQuery,
  ];

}
