update_enable_full: 0
event_enable_full: 0
article_enable_full: 0
landingpage_enable_full: 1
rezghsdrtg_enable_full: 1
rezghsdrtg_template: ''
rezghsdrtg_template_lock: none
rezghsdrtg_allowed_blocks:
  core/all: core/all
  core/paragraph: core/paragraph
  core/image: core/image
  core/heading: core/heading
  core/gallery: core/gallery
  core/list: core/list
  core/quote: core/quote
  core/audio: core/audio
  core/button: core/button
  core/buttons: core/buttons
  core/code: core/code
  core/columns: core/columns
  core/column: core/column
  core/cover: core/cover
  core/embed: core/embed
  core/file: core/file
  core/freeform: core/freeform
  core/html: core/html
  core/media-text: core/media-text
  core/preformatted: core/preformatted
  core/pullquote: core/pullquote
  core/separator: core/separator
  core/block: core/block
  core/spacer: core/spacer
  core/subhead: core/subhead
  core/table: core/table
  core/text-columns: core/text-columns
  core/verse: core/verse
  core/video: core/video
  core-embed/all: core-embed/all
  core-embed/twitter: core-embed/twitter
  core-embed/youtube: core-embed/youtube
  core-embed/facebook: core-embed/facebook
  core-embed/instagram: core-embed/instagram
  core-embed/wordpress: core-embed/wordpress
  core-embed/soundcloud: core-embed/soundcloud
  core-embed/spotify: core-embed/spotify
  core-embed/flickr: core-embed/flickr
  core-embed/vimeo: core-embed/vimeo
  core-embed/amazon-kindle: core-embed/amazon-kindle
  core-embed/animoto: core-embed/animoto
  core-embed/cloudup: core-embed/cloudup
  core-embed/collegehumor: core-embed/collegehumor
  core-embed/crowdsignal: core-embed/crowdsignal
  core-embed/dailymotion: core-embed/dailymotion
  embed: embed
  core-embed/hulu: core-embed/hulu
  core-embed/imgur: core-embed/imgur
  core-embed/issuu: core-embed/issuu
  core-embed/kickstarter: core-embed/kickstarter
  core-embed/meetup-com: core-embed/meetup-com
  core-embed/mixcloud: core-embed/mixcloud
  core-embed/polldaddy: core-embed/polldaddy
  core-embed/reddit: core-embed/reddit
  core-embed/reverbnation: core-embed/reverbnation
  core-embed/screencast: core-embed/screencast
  core-embed/scribd: core-embed/scribd
  core-embed/slideshare: core-embed/slideshare
  core-embed/smugmug: core-embed/smugmug
  core-embed/speaker-deck: core-embed/speaker-deck
  core-embed/speaker: core-embed/speaker
  core-embed/tiktok: core-embed/tiktok
  core-embed/ted: core-embed/ted
  core-embed/tumblr: core-embed/tumblr
  core-embed/videopress: core-embed/videopress
  core-embed/wordpress-tv: core-embed/wordpress-tv
rezghsdrtg_allowed_drupal_blocks:
  drupalblock/all_chaos_tools: drupalblock/all_chaos_tools
  'entity_view:node': 'entity_view:node'
  'entity_view:taxonomy_term': 'entity_view:taxonomy_term'
  'entity_view:user': 'entity_view:user'
  'entity_view:webform': 'entity_view:webform'
  'entity_view:webform_submission': 'entity_view:webform_submission'
  drupalblock/all_core: drupalblock/all_core
  page_title_block: page_title_block
  drupalblock/all_formulare: drupalblock/all_formulare
  user_login_block: user_login_block
  search_form_block: search_form_block
  drupalblock/all_help: drupalblock/all_help
  help_block: help_block
  drupalblock/all_listen_ansichten_: drupalblock/all_listen_ansichten_
  'views_block:comments_recent-block_1': 'views_block:comments_recent-block_1'
  'views_block:content_recent-block_1': 'views_block:content_recent-block_1'
  'views_block:who_s_online-who_s_online_block': 'views_block:who_s_online-who_s_online_block'
  drupalblock/all_men_s: drupalblock/all_men_s
  'system_menu_block:find-us-on': 'system_menu_block:find-us-on'
  'system_menu_block:footer': 'system_menu_block:footer'
  'system_menu_block:main': 'system_menu_block:main'
  'system_menu_block:account': 'system_menu_block:account'
  drupalblock/all_ohano_account: drupalblock/all_ohano_account
  ohano_account__devmode_block: ohano_account__devmode_block
  drupalblock/all_ohano_appearance: drupalblock/all_ohano_appearance
  ohano_appearance__brightness_block: ohano_appearance__brightness_block
  ohano_appearance__color_shade_block: ohano_appearance__color_shade_block
  ohano_appearance__font_size_block: ohano_appearance__font_size_block
  drupalblock/all_ohano_core: drupalblock/all_ohano_core
  ohano_core__features_block: ohano_core__features_block
  drupalblock/all_ohano_profile: drupalblock/all_ohano_profile
  ohano_profile__profile_block: ohano_profile__profile_block
  drupalblock/all_system: drupalblock/all_system
  system_breadcrumb_block: system_breadcrumb_block
  system_messages_block: system_messages_block
  node_syndicate_block: node_syndicate_block
  system_powered_by_block: system_powered_by_block
  system_branding_block: system_branding_block
  'language_block:language_interface': 'language_block:language_interface'
  drupalblock/all_user: drupalblock/all_user
  drupalblock/all_webform: drupalblock/all_webform
  webform_block: webform_block
  webform_submission_limit_block: webform_submission_limit_block
  drupalblock/all_webformular-zugriff: drupalblock/all_webformular-zugriff
  webform_access_group_entity: webform_access_group_entity
landingpage_template: ''
landingpage_template_lock: none
landingpage_allowed_blocks:
  core/paragraph: core/paragraph
  core/image: core/image
  core/heading: core/heading
  core/gallery: core/gallery
  core/list: core/list
  core/quote: core/quote
  core/audio: core/audio
  core/button: core/button
  core/buttons: core/buttons
  core/code: core/code
  core/columns: core/columns
  core/column: core/column
  core/cover: core/cover
  core/embed: core/embed
  core/file: core/file
  core/freeform: core/freeform
  core/html: core/html
  core/media-text: core/media-text
  core/preformatted: core/preformatted
  core/pullquote: core/pullquote
  core/separator: core/separator
  core/block: core/block
  core/spacer: core/spacer
  core/subhead: core/subhead
  core/table: core/table
  core/text-columns: core/text-columns
  core/verse: core/verse
  core/video: core/video
  core/all: 0
  core-embed/all: 0
  core-embed/twitter: 0
  core-embed/youtube: 0
  core-embed/facebook: 0
  core-embed/instagram: 0
  core-embed/wordpress: 0
  core-embed/soundcloud: 0
  core-embed/spotify: 0
  core-embed/flickr: 0
  core-embed/vimeo: 0
  core-embed/amazon-kindle: 0
  core-embed/animoto: 0
  core-embed/cloudup: 0
  core-embed/collegehumor: 0
  core-embed/crowdsignal: 0
  core-embed/dailymotion: 0
  embed: 0
  core-embed/hulu: 0
  core-embed/imgur: 0
  core-embed/issuu: 0
  core-embed/kickstarter: 0
  core-embed/meetup-com: 0
  core-embed/mixcloud: 0
  core-embed/polldaddy: 0
  core-embed/reddit: 0
  core-embed/reverbnation: 0
  core-embed/screencast: 0
  core-embed/scribd: 0
  core-embed/slideshare: 0
  core-embed/smugmug: 0
  core-embed/speaker-deck: 0
  core-embed/speaker: 0
  core-embed/tiktok: 0
  core-embed/ted: 0
  core-embed/tumblr: 0
  core-embed/videopress: 0
  core-embed/wordpress-tv: 0
landingpage_allowed_drupal_blocks:
  drupalblock/all_chaos_tools: 0
  'entity_view:node': 0
  'entity_view:taxonomy_term': 0
  'entity_view:user': 0
  'entity_view:webform': 0
  'entity_view:webform_submission': 0
  drupalblock/all_core: 0
  page_title_block: 0
  drupalblock/all_formulare: 0
  user_login_block: 0
  search_form_block: 0
  drupalblock/all_help: 0
  help_block: 0
  drupalblock/all_listen_ansichten_: drupalblock/all_listen_ansichten_
  'views_block:comments_recent-block_1': 0
  'views_block:content_recent-block_1': 0
  'views_block:who_s_online-who_s_online_block': 0
  drupalblock/all_men_s: 0
  'system_menu_block:find-us-on': 0
  'system_menu_block:footer': 0
  'system_menu_block:main': 0
  'system_menu_block:account': 0
  drupalblock/all_ohano_account: 0
  ohano_account__devmode_block: 0
  drupalblock/all_ohano_appearance: 0
  ohano_appearance__brightness_block: 0
  ohano_appearance__color_shade_block: 0
  ohano_appearance__font_size_block: 0
  drupalblock/all_ohano_core: 0
  ohano_core__features_block: 0
  drupalblock/all_ohano_profile: 0
  ohano_profile__profile_block: 0
  drupalblock/all_system: 0
  system_breadcrumb_block: 0
  system_messages_block: 0
  node_syndicate_block: 0
  system_powered_by_block: 0
  system_branding_block: 0
  'language_block:language_interface': 0
  drupalblock/all_user: 0
  drupalblock/all_webform: 0
  webform_block: 0
  webform_submission_limit_block: 0
  drupalblock/all_webformular-zugriff: 0
  webform_access_group_entity: 0
