_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: de
uuid: 5ce3294f-0b1b-45d0-8725-f99a9aab3f23
name: ohano
mail: hello@ohano.me
slogan: ''
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: de
mail_notification: ''
