name: Check Drupal Coding Standard

on:
  push:
    branches:
      - main
      - beta
      - alpha
      - feature/*
      - fix/*
  pull_request:
    branches:
      - main
      - beta
      - alpha
      - feature/*
      - fix/*

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check all custom parts against the Drupal coding standard
        run: composer install && bin/phpcs
