name: PHP Linting

on:
  push:
    branches:
      - main
      - beta
      - alpha
      - feature/*
      - fix/*
  pull_request:
    branches:
      - main
      - beta
      - alpha
      - feature/*
      - fix/*

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint all custom files containing php code
        run: bin/lint
