name: Main Pipeline

on:
  push:
    branches:
      - main
      - beta
      - alpha
      - feature/*
      - fix/*
  pull_request:
    branches:
      - main
      - beta
      - alpha
      - feature/*
      - fix/*

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint all custom files containing php code
        run: bin/lint
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Builds the app by installing all dependencies
        run: composer install
  check-phpcs:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check all custom parts against the Drupal coding standard
        run: composer install && bin/phpcs
  check-phpstan:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check all custom parts by PHPStan
        run: composer install && bin/phpcs
  check-psalm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check all custom parts by Psalm
        run: composer install && bin/phpcs
  check-phpcpd:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check all custom parts by PHP Copy/Paste Detector
        run: composer install && bin/phpcs
  run-unit-tests:
    needs: [check-phpcs, check-phpstan, check-psalm, check-phpcpd]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Runs all unit tests
        run: composer install && bin/test -u
  run-functional-tests:
    needs: [check-phpcs, check-phpstan, check-psalm, check-phpcpd]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Runs all functional tests
        # TODO: Replace by actual functional tests
        run: echo "Done."
  deploy:
    needs: [run-unit-tests, run-functional-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploys the app
        run: echo "Done."
